import {CheckCircle2,ShieldCheck,ExternalLink} from 'lucide-react';import type {Policy} from '../types';import {Link} from 'react-router-dom';
export function Badge({children,tone='blue'}:{children:React.ReactNode;tone?:'blue'|'green'|'orange'|'red'|'gray'}){return <span className={`badge ${tone}`}>{children}</span>}
export function Score({value}:{value:number}){const tone=value>=90?'green':value>=75?'blue':value>=50?'orange':'red';return <div className={`score ${tone}`}><strong>{value}%</strong><span>{value>=90?'完全匹配':value>=75?'高度匹配':value>=50?'可培育申报':'条件不足'}</span></div>}
export function PolicyCard({policy,onToast}:{policy:Policy;onToast?:(s:string)=>void}){return <article className="card policy-card"><div className="policy-main"><div className="row wrap"><Badge tone="gray">{policy.level}</Badge><Badge>{policy.category}</Badge><span className="source"><ShieldCheck size={14}/> 官方来源可溯源</span></div><h3>{policy.title}</h3><p className="muted">{policy.policyNumber} · {policy.department}</p><div className="meta-grid"><span>适用区域<strong>{policy.region}</strong></span><span>支持方式<strong>{policy.supportType}</strong></span><span>参考范围<strong>{policy.supportRange}</strong></span><span>截止日期<strong>{policy.deadline}</strong></span></div></div><div className="policy-side"><Score value={policy.matchScore}/><span className="days">剩余 {Number(policy.id)*3+11} 天</span><div className="row"><Link className="btn secondary small" to={`/policy/${policy.id}`}>查看详情</Link><Link className="btn primary small" to={`/workspace/${policy.id}`}>开始申报</Link></div><button className="text-btn" onClick={()=>onToast?.('已收藏该政策')}>☆ 收藏政策</button></div></article>}
export function Disclaimer({compact=false}:{compact?:boolean}){return <div className={`disclaimer ${compact?'compact':''}`}><ShieldCheck size={20}/><div><strong>服务边界说明</strong><p>苏策通提供政策信息检索、企业条件匹配、申报材料生成和材料自检服务。结果仅供企业参考，不构成政府审批意见，最终以主管部门正式通知为准。</p></div></div>}
export function Empty({text}:{text:string}){return <div className="empty"><CheckCircle2 size={32}/><strong>{text}</strong><p>调整筛选条件或稍后重试。</p></div>}
export function LoadingSteps({active}:{active:number}){const s=['识别企业需求','读取企业档案','检索政策知识库','比对申报条件','生成匹配结果'];return <div className="loading-steps">{s.map((x,i)=><div className={i<active?'done':i===active?'active':''} key={x}><i>{i<active?'✓':i+1}</i><span>{i===active?'正在':''}{x}</span></div>)}</div>}
export function DemoTag(){return <span className="demo-tag">演示数据 · 仅用于产品功能展示</span>}
export function ExternalMock(){return <span className="source"><ExternalLink size={13}/> 官方页面（Mock）</span>}
